"use client";
import {useEffect,useState} from "react";
type Item={id?:number;type:string;title:string;subtitle:string;date:string;url:string;imageKey:string;language:string;position:number};
const empty:Item={type:"project",title:"",subtitle:"",date:"",url:"",imageKey:"",language:"",position:0};
export default function AdminClient(){
 const [items,setItems]=useState<Item[]>([]),[settings,setSettings]=useState<Record<string,string>>({}),[form,setForm]=useState<Item>(empty),[status,setStatus]=useState("");
 const load=()=>fetch("/api/content").then(r=>r.json()).then(d=>{setItems(d.items.map((x:any)=>({...x,imageKey:x.image_key})));setSettings(d.settings)});
 useEffect(()=>{load()},[]);
 async function save(){setStatus("Saving…");await fetch("/api/admin/content",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({item:form})});setForm(empty);await load();setStatus("Published on the website");}
 async function setting(key:string){await fetch("/api/admin/content",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({kind:"setting",key,value:settings[key]||""})});setStatus("Published on the website");}
 async function remove(id?:number){if(!id||!confirm("Delete this item?"))return;await fetch("/api/admin/content",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({kind:"delete",id})});load();}
 async function upload(file:File){const fd=new FormData();fd.append("file",file);setStatus("Uploading…");const r=await fetch("/api/admin/upload",{method:"POST",body:fd});const d=await r.json();setForm({...form,imageKey:d.key});setStatus("File uploaded");}
 return <main className="admin-shell"><header className="admin-head"><div><p>ELDAR NEBOLSIN</p><h1>Website administration</h1></div><a href="/" target="_blank">View website ↗</a></header>
 <section className="admin-card"><h2>Texts and contact</h2>{[["contactEmail","Contact email"],["gramophoneQuote","Gramophone quote"],["bbcQuote","BBC quote"],["bioEnglish","Biography · English"],["bioSpanish","Biografía · Español"]].map(([k,l])=><label key={k}>{l}<textarea value={settings[k]||""} onChange={e=>setSettings({...settings,[k]:e.target.value})}/><button onClick={()=>setting(k)}>Publish change</button></label>)}</section>
 <section className="admin-card"><h2>Add or edit content</h2><div className="admin-grid"><label>Section<select value={form.type} onChange={e=>setForm({...form,type:e.target.value})}><option value="project">Concert / project</option><option value="recording">Recording</option><option value="photo">Downloadable photo</option><option value="biography">Downloadable biography</option></select></label><label>Title<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Details<input value={form.subtitle} onChange={e=>setForm({...form,subtitle:e.target.value})}/></label><label>Date / year<input value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/></label><label>External link<input value={form.url} onChange={e=>setForm({...form,url:e.target.value})}/></label><label>Language<input value={form.language} onChange={e=>setForm({...form,language:e.target.value})}/></label><label>Order<input type="number" value={form.position} onChange={e=>setForm({...form,position:Number(e.target.value)})}/></label><label>Cover, photo or PDF<input type="file" accept="image/*,.pdf" onChange={e=>e.target.files?.[0]&&upload(e.target.files[0])}/></label></div><button className="primary" disabled={!form.title} onClick={save}>{form.id?"Save changes":"Add and publish"}</button><span className="status">{status}</span></section>
 <section className="admin-card"><h2>Current content</h2><div className="items">{items.map(x=><article key={x.id}><div><small>{x.type} · {x.date||"No date"} · order {x.position}</small><strong>{x.title}</strong><span>{x.subtitle}</span></div><div><button onClick={()=>setForm(x)}>Edit</button><button onClick={()=>remove(x.id)}>Delete</button></div></article>)}</div></section></main>
}
